//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RBVH.Stada.Intranet.Resources.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RBVHStadaMasterPage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RBVHStadaMasterPage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RBVH.Stada.Intranet.Resources.Resources.RBVHStadaMasterPage", typeof(RBVHStadaMasterPage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounting.
        /// </summary>
        internal static string Accounting_TopMenu {
            get {
                return ResourceManager.GetString("Accounting_TopMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration &amp; Human Resource.
        /// </summary>
        internal static string AdminHR_TopMenu {
            get {
                return ResourceManager.GetString("AdminHR_TopMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analytical Development.
        /// </summary>
        internal static string AnalyticalDevelopment_TopMenu {
            get {
                return ResourceManager.GetString("AnalyticalDevelopment_TopMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Trip.
        /// </summary>
        internal static string BusinessTrip_LeftMenu {
            get {
                return ResourceManager.GetString("BusinessTrip_LeftMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Shift Request.
        /// </summary>
        internal static string ChangeShiftRequest_LeftMenu {
            get {
                return ResourceManager.GetString("ChangeShiftRequest_LeftMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Shift Request Task List.
        /// </summary>
        internal static string ChangeShiftRequestTaskList_LeftMenu {
            get {
                return ResourceManager.GetString("ChangeShiftRequestTaskList_LeftMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departments.
        /// </summary>
        internal static string Departments_TopMenu {
            get {
                return ResourceManager.GetString("Departments_TopMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design Request.
        /// </summary>
        internal static string DesignRequest_LeftMenu {
            get {
                return ResourceManager.GetString("DesignRequest_LeftMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diploma Supplement Request.
        /// </summary>
        internal static string DiplomaSupplementRequest_LeftMenu {
            get {
                return ResourceManager.GetString("DiplomaSupplementRequest_LeftMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information of Domestic Dossier.
        /// </summary>
        internal static string DissoierForDomesticRequest_LeftMenu {
            get {
                return ResourceManager.GetString("DissoierForDomesticRequest_LeftMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information of Exporting Dossier.
        /// </summary>
        internal static string DissoierForExportingRequest_LeftMenu {
            get {
                return ResourceManager.GetString("DissoierForExportingRequest_LeftMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Shift Time.
        /// </summary>
        internal static string EmployeeShiftTime_LeftMenu {
            get {
                return ResourceManager.GetString("EmployeeShiftTime_LeftMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engineering.
        /// </summary>
        internal static string Engineering_TopMenu {
            get {
                return ResourceManager.GetString("Engineering_TopMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        internal static string Forms_Admin {
            get {
                return ResourceManager.GetString("Forms_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forms.
        /// </summary>
        internal static string Forms_TopMenu {
            get {
                return ResourceManager.GetString("Forms_TopMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formulation Development.
        /// </summary>
        internal static string FormulationDevelopment_TopMenu {
            get {
                return ResourceManager.GetString("FormulationDevelopment_TopMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guess Welcoming Request.
        /// </summary>
        internal static string GuessWelcomingRequest_LeftMenu {
            get {
                return ResourceManager.GetString("GuessWelcomingRequest_LeftMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import - Export.
        /// </summary>
        internal static string ImportExport_TopMenu {
            get {
                return ResourceManager.GetString("ImportExport_TopMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information Update Request.
        /// </summary>
        internal static string InformationUpdateRequest_LeftMenu {
            get {
                return ResourceManager.GetString("InformationUpdateRequest_LeftMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal News.
        /// </summary>
        internal static string InternalNews_TopMenu {
            get {
                return ResourceManager.GetString("InternalNews_TopMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT.
        /// </summary>
        internal static string IT_TopMenu {
            get {
                return ResourceManager.GetString("IT_TopMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Approval List.
        /// </summary>
        internal static string LeaveApprovalList_LeftMenu {
            get {
                return ResourceManager.GetString("LeaveApprovalList_LeftMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Request.
        /// </summary>
        internal static string LeaveRequest_LeftMenu {
            get {
                return ResourceManager.GetString("LeaveRequest_LeftMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License To Transport.
        /// </summary>
        internal static string LicenseToTransport_LeftMenu {
            get {
                return ResourceManager.GetString("LicenseToTransport_LeftMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liquid Workshop.
        /// </summary>
        internal static string LiquidWorkshop_TopMenu {
            get {
                return ResourceManager.GetString("LiquidWorkshop_TopMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting Room Booking.
        /// </summary>
        internal static string MeetingRoomBooking_LeftMenu {
            get {
                return ResourceManager.GetString("MeetingRoomBooking_LeftMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Overtime.
        /// </summary>
        internal static string MyOverTime_LeftMenu {
            get {
                return ResourceManager.GetString("MyOverTime_LeftMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non conforming Report.
        /// </summary>
        internal static string NotConfirmingRequest_LeftMenu {
            get {
                return ResourceManager.GetString("NotConfirmingRequest_LeftMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overtime Approval List.
        /// </summary>
        internal static string OvertimeApprovalList_LeftMenu {
            get {
                return ResourceManager.GetString("OvertimeApprovalList_LeftMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overtime Request.
        /// </summary>
        internal static string OvertimeRequest_LeftMenu {
            get {
                return ResourceManager.GetString("OvertimeRequest_LeftMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planning.
        /// </summary>
        internal static string Planning_TopMenu {
            get {
                return ResourceManager.GetString("Planning_TopMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policies.
        /// </summary>
        internal static string Policies_TopMenu {
            get {
                return ResourceManager.GetString("Policies_TopMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procurement.
        /// </summary>
        internal static string Procurement_TopMenu {
            get {
                return ResourceManager.GetString("Procurement_TopMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality Assurance.
        /// </summary>
        internal static string QuanlityAssurance_TopMenu {
            get {
                return ResourceManager.GetString("QuanlityAssurance_TopMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality Control.
        /// </summary>
        internal static string QuanlityControl_TopMenu {
            get {
                return ResourceManager.GetString("QuanlityControl_TopMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recruitment Request.
        /// </summary>
        internal static string RecruitmentRequest_LeftMenu {
            get {
                return ResourceManager.GetString("RecruitmentRequest_LeftMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register For Transportation.
        /// </summary>
        internal static string RegisterForTransportation_LeftMenu {
            get {
                return ResourceManager.GetString("RegisterForTransportation_LeftMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regulatory Affair.
        /// </summary>
        internal static string RegulatoryAffair_TopMenu {
            get {
                return ResourceManager.GetString("RegulatoryAffair_TopMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Form.
        /// </summary>
        internal static string RequestForm_LeftMenu {
            get {
                return ResourceManager.GetString("RequestForm_LeftMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Leave of Absense For Overtime Work.
        /// </summary>
        internal static string RequesttoNotOvertime_LeftMenu {
            get {
                return ResourceManager.GetString("RequesttoNotOvertime_LeftMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Leave of Absense For Overtime Work Task List.
        /// </summary>
        internal static string RequesttoNotOvertimeTaskList_LeftMenu {
            get {
                return ResourceManager.GetString("RequesttoNotOvertimeTaskList_LeftMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requisition Of Documents.
        /// </summary>
        internal static string RequisitionOfDocuments_LeftMenu {
            get {
                return ResourceManager.GetString("RequisitionOfDocuments_LeftMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R&amp;D.
        /// </summary>
        internal static string RnD_LeftMenu {
            get {
                return ResourceManager.GetString("RnD_LeftMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Research &amp; Development.
        /// </summary>
        internal static string RnD_TopMenu {
            get {
                return ResourceManager.GetString("RnD_TopMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Approval List.
        /// </summary>
        internal static string ShiftApprovalList_LeftMenu {
            get {
                return ResourceManager.GetString("ShiftApprovalList_LeftMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Shift Request.
        /// </summary>
        internal static string ShiftManagement_MShiftRequestTitle {
            get {
                return ResourceManager.GetString("ShiftManagement_MShiftRequestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Request.
        /// </summary>
        internal static string ShiftRequest_LeftMenu {
            get {
                return ResourceManager.GetString("ShiftRequest_LeftMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solid workshop.
        /// </summary>
        internal static string Solidworkshop_TopMenu {
            get {
                return ResourceManager.GetString("Solidworkshop_TopMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stationary Request.
        /// </summary>
        internal static string StationaryRequest_LeftMenu {
            get {
                return ResourceManager.GetString("StationaryRequest_LeftMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Meeting Request.
        /// </summary>
        internal static string SupplierMeetingRequest_LeftMenu {
            get {
                return ResourceManager.GetString("SupplierMeetingRequest_LeftMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technology Transfer.
        /// </summary>
        internal static string TechnologyTransfer_TopMenu {
            get {
                return ResourceManager.GetString("TechnologyTransfer_TopMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timesheet.
        /// </summary>
        internal static string TimeSheet_LeftMenu {
            get {
                return ResourceManager.GetString("TimeSheet_LeftMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle  Request.
        /// </summary>
        internal static string TransportRequest_LeftMenu {
            get {
                return ResourceManager.GetString("TransportRequest_LeftMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle  Work Task List.
        /// </summary>
        internal static string TransportTaskList_LeftMenu {
            get {
                return ResourceManager.GetString("TransportTaskList_LeftMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse.
        /// </summary>
        internal static string Warehouse_TopMenu {
            get {
                return ResourceManager.GetString("Warehouse_TopMenu", resourceCulture);
            }
        }
    }
}
