//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace RBVH.Stada.Intranet.WebPages.CONTROLTEMPLATES.RBVH.Stada.Controls.ChangeShiftManagementControl {
    
    
    public partial class ChangeShiftApprovalControl {
        
        /// <summary>
        /// ParamShiftApprovalApproverIDHidden control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField ParamShiftApprovalApproverIDHidden;
        
        /// <summary>
        /// ChangeShiftApprovalWebPartZone control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Microsoft.SharePoint.WebPartPages.WebPartZone ChangeShiftApprovalWebPartZone;
        
        /// <summary>
        /// ChangeShiftApprovalWebPart control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Microsoft.SharePoint.WebPartPages.XsltListViewWebPart ChangeShiftApprovalWebPart;
    }
}
